version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - lab_rabbitmq_data:/var/lib/rabbitmq/
        - lab_rabbitmq_logs:/var/log/rabbitmq/
volumes:
  lab_rabbitmq_data:
  lab_rabbitmq_logs: