entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"

raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node1:9200" ]
        index_type: trace-analytics-raw

service-map-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node1:9200" ]
        index_type: trace-analytics-service-map
        trace_analytics_service_map: true

metrics-pipeline:
  source:
    otel_metrics_source:
      ssl: false
  processor:
    - otel_metrics_raw_processor:
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node1:9200" ]
        insecure: true
        index: metrics-otel-v1-%{yyyy.MM.dd}

otel-logs-pipeline:
  source:
    otel_logs_source:
      ssl: false
    processor:
    - otel_logs_raw_processor:
  sink:
    - opensearch:
        hosts: ["http://opensearch-node1:9200"]
        index: app-logs
        insecure: true